### ISSUE TITLE
cannot have arrays in areas

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/amphora#115]
If the page area points to an array (rather than just a string/ref), byline breaks when serving it:

This happens when the page data looks like:

``` yaml
layout: /components/layout/instances/article
    head:
      - /components/title/instances/0
      - /components/canonical-url/instances/0
    main: /components/article/instances/pr-first
```

Full error (the first bit is the data composer thinks it's working with.

```
{ _ref: 
   [ '/components/title/instances/0',
     '/components/canonical-url/instances/0' ] }
TypeError: ref.match is not a function
   at /Users/npecora/www/byline/lib/composer.js:37:64
   at baseFindIndex (/Users/npecora/www/byline/node_modules/lodash/index.js:326:11)
   at Function.<anonymous> (/Users/npecora/www/byline/node_modules/lodash/index.js:3241:23)
   at /Users/npecora/www/byline/lib/composer.js:37:19
   at tryCatcher (/Users/npecora/www/byline/node_modules/bluebird/js/main/util.js:24:31)
   at ReductionPromiseArray._promiseFulfilled (/Users/npecora/www/byline/node_modules/bluebird/js/main/reduce.js:103:38)
   at Promise._settlePromiseAt (/Users/npecora/www/byline/node_modules/bluebird/js/main/promise.js:535:26)
   at Promise._settlePromises (/Users/npecora/www/byline/node_modules/bluebird/js/main/promise.js:646:14)
   at Async._drainQueue (/Users/npecora/www/byline/node_modules/bluebird/js/main/async.js:182:16)
   at Async._drainQueues (/Users/npecora/www/byline/node_modules/bluebird/js/main/async.js:192:10)
   at Immediate.Async.drainQueues [as _onImmediate] (/Users/npecora/www/byline/node_modules/bluebird/js/main/async.js:15:14)
   at processImmediate [as _immediateCallback] (timers.js:371:17)
```
