### ISSUE TITLE
page-specific components don't get host+path prepended in their data when they're in arrays

### ISSUE THREAD

**Issue by yoshokatana** [nymag/amphora#182]
It works if they're properties of the page

```
pages:
  one:
    someComponent: /components/clay-meta-url/instances/0
components:
  clay-meta-url:
    instances:
      -
        url: 2015/09/introducing-press-room.html
```

that url will become `<host>/<path>/2015/09/introducing-press-room.html`

It does **NOT** work if they're in an array

```
pages:
  one:
    - /components/clay-meta-url/instances/0
components:
  clay-meta-url:
    instances:
      -
        url: 2015/09/introducing-press-room.html
```
